Using /run as tmpfs

diff --git a/src/usr/lib/sectpmctl/scripts/sectpmctl-boot b/src/usr/lib/sectpmctl/scripts/sectpmctl-boot
--- a/src/usr/lib/sectpmctl/scripts/sectpmctl-boot
+++ b/src/usr/lib/sectpmctl/scripts/sectpmctl-boot
@@ -256,9 +256,13 @@ create_efi_blob ()
     echo -n "Found          : ${linux}, ${initrd}"
   fi
 
-  ramdir=$(mktemp -d -p /tmp)
-  mount -t tmpfs tmpfs "${ramdir}"
-  tempbootdir=$(mktemp -d -p "${ramdir}")
+  p1="$( grep -c "^tmpfs /run tmpfs" /proc/mounts )" || p1=""
+  if [[ "${p1}" != "1" ]]; then
+    echo "Mounted tmpfs /run is required"
+    exit
+  fi
+  install -d -m 600 "/run/sectpmctl" || exit
+  tempbootdir=$(mktemp -d -p "/run/sectpmctl")
   chmod 700 "${tempbootdir}"
   cd "${tempbootdir}" || exit
 
@@ -339,7 +343,6 @@ create_efi_blob ()
   shred -f -z -u cmdline os-release
   cd - > /dev/null || exit
   rmdir "${tempbootdir}"
-  umount "${ramdir}"
 }
 
 get_installed_kernel_list( )
@@ -627,9 +630,13 @@ install ()
 
   cd - > /dev/null || exit
 
-  ramdir=$(mktemp -d -p /tmp)
-  mount -t tmpfs tmpfs "${ramdir}"
-  tempdirname=$(mktemp -d -p "${ramdir}")
+  p1="$( grep -c "^tmpfs /run tmpfs" /proc/mounts )" || p1=""
+  if [[ "${p1}" != "1" ]]; then
+    echo "Mounted tmpfs /run is required"
+    exit
+  fi
+  install -d -m 600 "/run/sectpmctl" || exit
+  tempdirname=$(mktemp -d -p "/run/sectpmctl")
   chmod 700 "${tempdirname}"
   cd "${tempdirname}" || exit
 
@@ -699,7 +706,6 @@ install ()
   shred -f -z -u ./*.auth ./*.cer ./*.crt ./*.esl ./*.key ./*.priv ./*.pub ./*.ctx ./*.obj
   cd - > /dev/null || exit
   rmdir "${tempdirname}"
-  umount "${ramdir}"
 
   # configure framework.conf of dkms for ubuntu 22.04 if installed to add the sign helper script
   # and framework.conf.d of dkms for ubuntu >= 22.10 in any case to support upgrades
diff --git a/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm b/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm
--- a/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm
+++ b/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm
@@ -585,9 +585,13 @@ do_provisioning() {
     tpm2_changeauth -Q --object-context=lockout "$(cat "${LOCKOUT_FILE}")"
   fi
 
-  ramdir=$(mktemp -d -p /tmp)
-  mount -t tmpfs tmpfs "${ramdir}"
-  tempdir=$(mktemp -d -p "${ramdir}")
+  p1="$( grep -c "^tmpfs /run tmpfs" /proc/mounts )" || p1=""
+  if [[ "${p1}" != "1" ]]; then
+    echo "Mounted tmpfs /run is required"
+    exit
+  fi
+  install -d -m 600 "/run/sectpmctl" || exit
+  tempdir=$(mktemp -d -p "/run/sectpmctl")
   chmod 700 "${tempdir}"
   cd "${tempdir}" || exit
 
@@ -619,7 +623,6 @@ do_provisioning() {
 
   cd - > /dev/null || exit
   rmdir "${tempdir}"
-  umount "${ramdir}"
 }
 
 generate_unseal_script() {
@@ -898,12 +901,16 @@ generate_tpm2_policy() {
 
   echo "## CRYPT PARTITION: ${CRYPT_PARTITION}"
 
+  p1="$( grep -c "^tmpfs /run tmpfs" /proc/mounts )" || p1=""
+  if [[ "${p1}" != "1" ]]; then
+    echo "Mounted tmpfs /run is required"
+    exit 1
+  fi
+  install -d -m 600 "/run/sectpmctl" || exit 1
   TEMPDIR=""
-  TEMPDIR="$(mktemp -d -p /tmp)"
+  TEMPDIR="$(mktemp -d -p "/run/sectpmctl")"
   chmod 700 "${TEMPDIR}"
   TPM_SECRET_LUKS_KEY="tpmkey"
-
-  mount -t tmpfs "${TEMPDIR##*/}" "${TEMPDIR}"
 
   echo "CREATE AND ADD TPM POLICY IN TMPFS DIRECTORY ${TEMPDIR}"
   cd "${TEMPDIR}" || exit 1
@@ -1037,7 +1044,6 @@ generate_tpm2_policy() {
   shred -f -z -u "${TPM_SECRET_LUKS_KEY}"
   
   cd - > /dev/null
-  umount "${TEMPDIR}"
   rmdir "${TEMPDIR}"
   
   echo "DONE"
