Initial fix to support Linux AARCH4 with UEFI

diff --git a/src/usr/lib/sectpmctl/scripts/sectpmctl-boot b/src/usr/lib/sectpmctl/scripts/sectpmctl-boot
--- a/src/usr/lib/sectpmctl/scripts/sectpmctl-boot
+++ b/src/usr/lib/sectpmctl/scripts/sectpmctl-boot
@@ -105,24 +105,24 @@ setup_systemd_boot ()
   block_device=$(lsblk -pndo pkname "${partition}")
   block_device_partition_number=$(gdisk -l "${block_device}" | grep -i ef00 | awk '{print $1 " " $2}' | grep "${partition_offset}" | awk '{print $1}')
 
-  if [ -f "${SECTPMCTL_EFI_DIR}/systemd-bootx64.efi" ]; then
-    rm "${SECTPMCTL_EFI_DIR}/systemd-bootx64.efi"
+  if [ -f "${SECTPMCTL_EFI_DIR}/systemd-bootaa64.efi" ]; then
+    rm "${SECTPMCTL_EFI_DIR}/systemd-bootaa64.efi"
   fi
 
-  /usr/lib/sectpmctl/scripts/sbsign.sh --key "${SECTPMCTL_KEYS}/db.obj" --cert "${SECTPMCTL_KEYS}/db.crt" --output "${SECTPMCTL_EFI_DIR}/systemd-bootx64.efi" "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" > /dev/null 2> /dev/null
-  if ! sbverify --cert "${SECTPMCTL_KEYS}/db.crt" "${SECTPMCTL_EFI_DIR}/systemd-bootx64.efi" 2> /dev/null > /dev/null; then
-    echo "Error: Could not sign efi bootloader systemd-bootx64.efi"
+  /usr/lib/sectpmctl/scripts/sbsign.sh --key "${SECTPMCTL_KEYS}/db.obj" --cert "${SECTPMCTL_KEYS}/db.crt" --output "${SECTPMCTL_EFI_DIR}/systemd-bootaa64.efi" "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" > /dev/null 2> /dev/null
+  if ! sbverify --cert "${SECTPMCTL_KEYS}/db.crt" "${SECTPMCTL_EFI_DIR}/systemd-bootaa64.efi" 2> /dev/null > /dev/null; then
+    echo "Error: Could not sign efi bootloader systemd-bootaa64.efi"
     exit 3
   fi
 
-  hasBootEntry=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -ci "\\\\efi\\\\sectpmctl\\\\systemd-bootx64.efi")
+  hasBootEntry=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -ci "\\\\efi\\\\sectpmctl\\\\systemd-bootaa64.efi")
   if [ ! "$hasBootEntry" == "1" ]; then
-    efibootmgr --quiet --disk "${block_device}" --part "${block_device_partition_number}" --create --label "SECTPMCTL Bootloader" --loader "/EFI/sectpmctl/systemd-bootx64.efi"
+    efibootmgr --quiet --disk "${block_device}" --part "${block_device_partition_number}" --create --label "SECTPMCTL Bootloader" --loader "/EFI/sectpmctl/systemd-bootaa64.efi"
   fi
 
-  hasBootEntry=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -ci "\\\\efi\\\\sectpmctl\\\\systemd-bootx64.efi")
+  hasBootEntry=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -ci "\\\\efi\\\\sectpmctl\\\\systemd-bootaa64.efi")
   if [ "$hasBootEntry" == "1" ]; then
-    entryId=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -i "\\\\efi\\\\sectpmctl\\\\systemd-bootx64.efi" | sed -e 's/^Boot\([0-9]\+\)\(.*\)$/\1/')
+    entryId=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -i "\\\\efi\\\\sectpmctl\\\\systemd-bootaa64.efi" | sed -e 's/^Boot\([0-9]\+\)\(.*\)$/\1/')
 
     isDefaultEntry=$(efibootmgr -v | grep -c "^BootOrder: ${entryId}")
     if [ ! "$isDefaultEntry" == "1" ]; then
@@ -181,9 +181,9 @@ deactivate ()
   trap - ERR
 
   entryId=""
-  hasBootEntry=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -ci "\\\\efi\\\\sectpmctl\\\\systemd-bootx64.efi")
+  hasBootEntry=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -ci "\\\\efi\\\\sectpmctl\\\\systemd-bootaa64.efi")
   if [ "$hasBootEntry" == "1" ]; then
-    entryId=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -i "\\\\efi\\\\sectpmctl\\\\systemd-bootx64.efi" | sed -e 's/^Boot\([0-9]\+\)\(.*\)$/\1/')
+    entryId=$(efibootmgr -v | grep "SECTPMCTL Bootloader" | grep -i "\\\\efi\\\\sectpmctl\\\\systemd-bootaa64.efi" | sed -e 's/^Boot\([0-9]\+\)\(.*\)$/\1/')
     efibootmgr -q -b "${entryId}" -A
   fi
   isEntryActive=$(efibootmgr -v | grep -c "^Boot${entryId}\*")
@@ -316,18 +316,31 @@ create_efi_blob ()
       rm "/boot/efi/EFI/Linux/sectpmctl-${version}.efi"
     fi
 
-    maxkernelsize=16777216
-    actualsize="$( wc -c < "${linux}" )"
-    if [ ${actualsize} -ge ${maxkernelsize} ]; then
-        echo Error: kernel "${linux}" exceeds "${minimumsize}" bytes
-    fi
+    align="$(objdump -p "/usr/lib/systemd/boot/efi/linuxaa64.efi.stub" | awk '{ if ($1 == "SectionAlignment"){print $2} }')"
+    align=$((16#$align))
+    osrel_offs="$(objdump -h "/usr/lib/systemd/boot/efi/linuxaa64.efi.stub" | awk -W posix 'NF==7 {size="0x"$3; offset="0x"$4} END {print size + offset}')"
+    osrel_offs=$((osrel_offs + "$align" - osrel_offs % "$align"))
+    cmdline_offs=$((osrel_offs + $(stat -Lc%s "${tempbootdir}/os-release")))
+    cmdline_offs=$((cmdline_offs + "$align" - cmdline_offs % "$align"))
+    initrd_offs=$((cmdline_offs + $(stat -Lc%s "${tempbootdir}/cmdline")))
+    initrd_offs=$((initrd_offs + "$align" - initrd_offs % "$align"))
+    linux_offs=$((initrd_offs + $(stat -Lc%s "${initrd}")))
+    linux_offs=$((linux_offs + "$align" - linux_offs % "$align"))
+
+    cp "${linux}" "${tempbootdir}/vmlinuz.gz"
+    gunzip "${tempbootdir}/vmlinuz.gz"
 
     objcopy \
-        --add-section .osrel="${tempbootdir}/os-release" --change-section-vma .osrel=0x20000 \
-        --add-section .cmdline="${tempbootdir}/cmdline" --change-section-vma .cmdline=0x30000 \
-        --add-section .linux="${linux}" --change-section-vma .linux=0x2000000 \
-        --add-section .initrd="${initrd}" --change-section-vma .initrd=0x3800000 \
-        /usr/lib/systemd/boot/efi/linuxx64.efi.stub "${tempbootdir}/efi"
+        --add-section .osrel="${tempbootdir}/os-release" --change-section-vma .osrel=$(printf 0x%x $osrel_offs) \
+        --add-section .cmdline="${tempbootdir}/cmdline" \
+        --change-section-vma .cmdline=$(printf 0x%x $cmdline_offs) \
+        --add-section .initrd="${initrd}" \
+        --change-section-vma .initrd=$(printf 0x%x $initrd_offs) \
+        --add-section .linux="${tempbootdir}/vmlinuz" \
+        --change-section-vma .linux=$(printf 0x%x $linux_offs) \
+        "/usr/lib/systemd/boot/efi/linuxaa64.efi.stub" "${tempbootdir}/efi"
+
+    rm "${tempbootdir}/vmlinuz"
 
     /usr/lib/sectpmctl/scripts/sbsign.sh --key "${SECTPMCTL_KEYS}/db.obj" --cert "${SECTPMCTL_KEYS}/db.crt" --output "/boot/efi/EFI/Linux/sectpmctl-${version}.efi" "${tempbootdir}/efi" > /dev/null 2> /dev/null
     if ! sbverify --cert "${SECTPMCTL_KEYS}/db.crt" "/boot/efi/EFI/Linux/sectpmctl-${version}.efi" 2> /dev/null > /dev/null; then
@@ -618,10 +631,6 @@ install ()
         exit 3
       fi
     fi
-    if [ "x${skip_dbx}" = "x1" ] && [ ! "$( efi-readvar | grep -c 'Variable dbx has no entries')" = 0 ]; then
-      echo 'The "--skipdbx" option seems not to be needed, please remove it from the call.'
-      exit 3
-    fi
   fi
 
   cd "${SECTPMCTL_KEYS}" || exit
@@ -707,7 +716,6 @@ install ()
   fi
   efi-updatevar -f KEK.auth KEK
   efi-updatevar -f PK.auth PK
-  chattr +i /sys/firmware/efi/efivars/dbx-d719b2cb-3d3a-4596-a3bc-dad00e67656f
   chattr +i /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f
   chattr +i /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c
   chattr +i /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c
