Fixed TPM_RC_PCR_CHANGED and added documentation

diff --git a/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm b/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm
--- a/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm
+++ b/src/usr/lib/sectpmctl/scripts/sectpmctl-tpm
@@ -538,6 +538,10 @@ generate_unseal_script() {
   EXTEND="${5}"
   SECTPMCTL_KEYS="${6}"
   TPM_PASSWORD="${7}"
+  
+  # settings for retries in passwordless unsealing
+  UNSEAL_RETRY_COUNT="5"
+  UNSEAL_RETRY_SLEEP="2"
 
   CREATE_PRIMARY_HASH="sha256"
   if [[ $(tpm2_getcap algorithms | grep -c 'sha384:') == 1 ]]; then
@@ -584,7 +588,9 @@ read -sr password || true
 echo
 
 sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --password "\${password}" --pcr-extend 1>&3 3>&-
-if [ \$? -ne 0 ]; then
+retValUnseal=\$?
+
+if [ \$retValUnseal -ne 0 ]; then
         umount /dev/shm
         echo UNSEAL FAILED, CHECKING RECOVERY KEY
         echo -n "\${password}" 1>&3 3>&-
@@ -592,9 +598,11 @@ if [ \$? -ne 0 ]; then
 fi
 
 sectpmctl key extend --random
+retValExtend=\$?
 
-sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --password "\${password}" --pcr-extend > /dev/null 2> /dev/null
-if [ \$? -eq 0 ]; then
+umount /dev/shm
+
+if [ \$retValExtend -ne 0 ]; then
         echo KEY COULD NOT BE SECURED. PLEASE REBOOT.
         echo
         while true; do
@@ -627,23 +635,31 @@ if [ "\$CRYPTTAB_TRIED" = 0 ]; then
         sectpmctl key extend --file luks.dat
         shred -f -z -u luks.dat
 
-        sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --noda --pcr-extend 1>&3 3>&-
-        retVal=\$?
+        retValUnseal=1
+        for _ in {1..${UNSEAL_RETRY_COUNT}}; do
+                sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --noda --pcr-extend 1>&3 3>&-
+                retValUnseal=\$?
+
+                if [ \$retValUnseal -eq 0 ]; then
+                        break
+                else
+                        echo Kernel maybe busy, please wait
+                        sleep ${UNSEAL_RETRY_SLEEP}
+                fi
+        done
 
         sectpmctl key extend --random
-
-        sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --noda --pcr-extend > /dev/null 2> /dev/null
-        retValTest=\$?
+        retValExtend=\$?
 
         umount /dev/shm
         
-        if [ \$retVal -ne 0 ]; then
+        if [ \$retValUnseal -ne 0 ]; then
                 echo UNSEAL FAILED
                 echo
                 exit 1
         fi
         
-        if [ \$retValTest -eq 0 ]; then
+        if [ \$retValExtend -ne 0 ]; then
                 echo KEY COULD NOT BE SECURED. PLEASE REBOOT.
                 echo
                 while true; do
@@ -682,12 +698,22 @@ if [ "\$CRYPTTAB_TRIED" = 0 ]; then
         sectpmctl key extend --file luks.dat
         shred -f -z -u luks.dat
 
-        sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --noda --pcr-extend --pcr-preseed 1>&3 3>&-
-        retVal=\$?
+        retValUnseal=1
+        for _ in {1..${UNSEAL_RETRY_COUNT}}; do
+                sectpmctl key unseal --handle "${PERSISTANT_HANDLE_TO_USE}" --noda --pcr-extend --pcr-preseed 1>&3 3>&-
+                retValUnseal=\$?
+
+                if [ \$retValUnseal -eq 0 ]; then
+                        break
+                else
+                        echo Kernel maybe busy, please wait
+                        sleep ${UNSEAL_RETRY_SLEEP}
+                fi
+        done
 
         umount /dev/shm
         
-        if [ \$retVal -ne 0 ]; then
+        if [ \$retValUnseal -ne 0 ]; then
                 echo UNSEAL FAILED
                 echo
                 exit 1
